language: python
before_install:
  - sudo apt-get install -y libvirt-dev
python:
  - "2.7"
  - "3.4"
install: "pip install -r requirements-dev.txt"
script: python setup.py test --addopts '--cov vadvisor'
